version: '3.8'
services:
  nginx:
    image: nginx:1.27.1-alpine-slim
    container_name: website_host
    restart: unless-stopped
    ports:
      - 8089:80
    volumes:
      - ./src/:/usr/share/nginx/html